spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persons
    username: program  # SQL dosyasında oluşturulan kullanıcı
    password: test     # SQL dosyasında belirtilen şifre
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: always  # SQL dosyalarını her zaman başlatır (genelde geliştirme sırasında kullanılır)
    schema-locations: classpath:db/schema.sql  # Veritabanı şeması için SQL dosyası (varsa)
    data-locations: classpath:db/data.sql  # Veritabanı verileri için SQL dosyası (varsa)

server:
  port: 8080  # Uygulamanın çalışacağı port (bu sunucunun HTTP portudur, PostgreSQL ile karışmamalıdır)
