name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Uygulamayı derle ve test et
      - name: Build and Test
        run: ./gradlew build

      # Uygulamayı Heroku'ya dağıt
      - name: Deploy to Heroku
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker build -t registry.heroku.com/<lab1-template>/web .
          docker push registry.heroku.com/<lab1-template>/web
          heroku container:release web --app <lab1-template>

      # Postman API Testlerini Çalıştır
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true